version: '3.8'

services:
#  damn:
#    build:
#      context: ./
#    command: ["./damn"]
#    ports:
#      - "8080:8080"
#    env_file:
#      - .env
#    depends_on:
#      - db
#    container_name: damn

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - ${DB_PORT_EXTERNAL}:${DB_PORT_INTERNAL}
    volumes:
      - ./migrations:/docker-entrypoint-initdb.d:ro
    container_name: db

volumes:
  postgres_data: