@TOKEN =eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsInJvbGUiOiJhZG1pbiIsImV4cCI6MTcxMTAyMDQzOH0.pe6lQGjTgvBvIeNMKu_DHgMI1KGLVkFDE-kAR4fMfR8

###

# curl -X GET http://localhost:8080/admin/violations
#-H "Authorization: Bearer ${TOKEN}"
GET http://localhost:8080/admin/violations
Authorization: Bearer {{TOKEN}}

###
# curl -X PATCH http://localhost:8080/admin/violations/4
#-H "Authorization: Bearer {{TOKEN}}"
#-H 'Content-Type: application/json'
#-d '{
#    "status": "рассмотрено"
#}'
PATCH http://localhost:8080/admin/violations/4
Authorization: Bearer {{TOKEN}}
Content-Type: application/json

{
  "status": "рассмотрено"
}

###


