@TOKEN =eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsInJvbGUiOiJhZG1pbiIsImV4cCI6MTcxMzc2NTc3N30.NNFJ8utzmWgrr-wB6khVZG_SePOLaF1_HXsBWim_Uc4

###

# curl -X GET http://localhost:8080/admin/violations
#-H "Authorization: Bearer ${TOKEN}"
GET http://localhost:8080/admin/violations
Authorization: Bearer {{TOKEN}}

###
# curl -X PATCH http://localhost:8080/admin/violations/4
#-H "Authorization: Bearer {{TOKEN}}"
#-H 'Content-Type: application/json'
#-d '{
#    "status": "рассмотрено"
#}'
PATCH http://localhost:8080/admin/violations/1
Authorization: Bearer {{TOKEN}}
Content-Type: application/json

{
  "status": "рассмотрено"
}

###


