# curl -X POST http://localhost:8080/register
#-H 'Content-Type: application/json'
#-d '{
#    "login": "new_user",
#    "password": "password123",
#    "fullName": "New User",
#    "phone": "+1234567890",
#    "email": "newuser@example.com"
#}'
POST http://localhost:8080/register
Content-Type: application/json

{
  "login": "new_user",
  "password": "password123",
  "fullName": "New User",
  "phone": "+1234567890",
  "email": "newuser@example.com"
}

###

# curl -X POST http://localhost:8080/login
#-H 'Content-Type: application/json'
#-d '{
#    "login": "new_user",
#    "password": "password123"
#}'
POST http://localhost:8080/login
Content-Type: application/json

{
  "login": "new_user",
  "password": "password123"
}

###



#account 2

# curl -X POST http://localhost:8080/register
#-H 'Content-Type: application/json'
#-d '{
#    "login": "new_user",
#    "password": "password123",
#    "fullName": "New User",
#    "phone": "+1234567890",
#    "email": "newuser@example.com"
#}'
POST http://localhost:8080/register
Content-Type: application/json

{
  "login": "111111211111",
  "password": "111111",
  "fullName": "N111111",
  "phone": "+2234567890",
  "email": "11111112111@example.com"
}

###

# curl -X POST http://localhost:8080/login
#-H 'Content-Type: application/json'
#-d '{
#    "login": "new_user",
#    "password": "password123"
#}'
POST http://localhost:8080/login
Content-Type: application/json

{
  "login": "new_use2r2",
  "password": "passwo2rd123"
}

###



